import './global.css';
import { Root } from '../providers/AuthProvider';
import React from 'react';

export const metadata = {
  title: 'Welcome to my-clicker',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Root>
          <div>
            {children}
          </div>
        </Root>
        </body>
    </html>
  );
}
